# Generated by Django 3.1.5 on 2021-02-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210210_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество на складе'),
        ),
    ]
